### ISSUE TITLE
karrot-docker_backend_* can't install python packages

### ISSUE THREAD

**Issue by decentral1se** [yunity/karrot-docker#4]
Just did a fresh `git pull` and ran `docker-compose up` and got this error.

Related to https://github.com/yunity/karrot-docker/commit/ee9c7b9824381923cd1b249c34b1fb8dfb7b485c?

Here's the log I saw:

```
➜  karrot-docker (master) ✔ docker logs -f karrot-docker_backend_1
Uninstalling codecov-2.0.15:
  Successfully uninstalled codecov-2.0.15
Uninstalling PyNaCl-1.3.0:
  Successfully uninstalled PyNaCl-1.3.0
Uninstalling asn1crypto-0.24.0:
  Successfully uninstalled asn1crypto-0.24.0
Uninstalling pyasn1-0.4.5:
  Successfully uninstalled pyasn1-0.4.5
Uninstalling keyring-10.1:
  Successfully uninstalled keyring-10.1
Cannot uninstall 'pycrypto'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
Traceback (most recent call last):
  File "/app/env/bin/pip-sync", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/piptools/scripts/sync.py", line 74, in cli
    install_flags=install_flags))
  File "/usr/local/lib/python3.5/dist-packages/piptools/sync.py", line 149, in sync
    check_call([pip, 'uninstall', '-y'] + pip_flags + sorted(to_uninstall))
  File "/usr/lib/python3.5/subprocess.py", line 271, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['pip', 'uninstall', '-y', 'ansible', 'asn1crypto', 'bcrypt', 'codecov', 'cryptography', 'keyring', 'keyrings.alt', 'paramiko', 'pyasn1', 'pycrypto', 'pygobject', 'pynacl', 'pyxdg', 'pyyaml', 'secretstorage', 'virtualenv']' returned non-zero exit status 1
Traceback (most recent call last):
  File "./manage.py", line 13, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named 'django'
Cannot uninstall 'pycrypto'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
Traceback (most recent call last):
  File "/app/env/bin/pip-sync", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/piptools/scripts/sync.py", line 74, in cli
    install_flags=install_flags))
  File "/usr/local/lib/python3.5/dist-packages/piptools/sync.py", line 149, in sync
    check_call([pip, 'uninstall', '-y'] + pip_flags + sorted(to_uninstall))
  File "/usr/lib/python3.5/subprocess.py", line 271, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['pip', 'uninstall', '-y', 'ansible', 'bcrypt', 'cryptography', 'keyrings.alt', 'paramiko', 'pycrypto', 'pygobject', 'pyxdg', 'pyyaml', 'secretstorage', 'virtualenv']' returned non-zero exit status 1
Traceback (most recent call last):
  File "./manage.py", line 13, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named 'django'
Cannot uninstall 'pycrypto'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
Traceback (most recent call last):
  File "/app/env/bin/pip-sync", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/piptools/scripts/sync.py", line 74, in cli
    install_flags=install_flags))
  File "/usr/local/lib/python3.5/dist-packages/piptools/sync.py", line 149, in sync
    check_call([pip, 'uninstall', '-y'] + pip_flags + sorted(to_uninstall))
  File "/usr/lib/python3.5/subprocess.py", line 271, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['pip', 'uninstall', '-y', 'ansible', 'bcrypt', 'cryptography', 'keyrings.alt', 'paramiko', 'pycrypto', 'pygobject', 'pyxdg', 'pyyaml', 'secretstorage', 'virtualenv']' returned non-zero exit status 1
Traceback (most recent call last):
  File "./manage.py", line 13, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named 'django'
Uninstalling cryptography-2.5:
  Successfully uninstalled cryptography-2.5
Uninstalling ansible-2.7.6:
Uninstalling ansible-2.7.6:
  Successfully uninstalled ansible-2.7.6
Cannot uninstall 'pygobject'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
Traceback (most recent call last):
  File "/app/env/bin/pip-sync", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/piptools/scripts/sync.py", line 74, in cli
    install_flags=install_flags))
  File "/usr/local/lib/python3.5/dist-packages/piptools/sync.py", line 149, in sync
    check_call([pip, 'uninstall', '-y'] + pip_flags + sorted(to_uninstall))
  File "/usr/lib/python3.5/subprocess.py", line 271, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['pip', 'uninstall', '-y', 'ansible', 'bcrypt', 'keyrings.alt', 'paramiko', 'pycrypto', 'pygobject', 'pyxdg', 'pyyaml', 'secretstorage', 'virtualenv']' returned non-zero exit status 1
Traceback (most recent call last):
  File "./manage.py", line 13, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named 'django'
```

**Comment by nicksellen** [comment]
Hmm, odd. It looks like pip-sync is fiddling with the system deps instead of the virtualenv ones. I wonder if we need to still have pip-tools installed inside the virtualenv.

...although the setup did work on my system when I originally made it - and a fresh setup now just worked fine.

I'll add a line to install a local pip-tools though and see if that helps.

**Comment by nicksellen** [comment]
I added it in https://github.com/yunity/karrot-docker/commit/d2cc160039ddfca9974c97c5f46ab11960b3c47f - can you see if that helps?

**Comment by decentral1se** [comment]
Hmmm, just ran it from fresh now and getting into a weird loop. Seems there are missing files:

```
karrot-docker_backend_1 exited with code 127                                                                                                                                                                                                                                                
mjml_1      | [4/4] Building fresh packages...                                                                                                                                                                  
mjml_1      | success Saved lockfile.                                                                                                                                                                                
mjml_1      | Done in 2.54s.                                                                          
mjml_1      | sh: 1: ./convert: not found                                                                                                                                                                                                                                                      
mjml_1      | yarn install v1.12.3                                                                                                                                                                                                             
mjml_1      | [1/4] Resolving packages...                                          
mjml_1      | success Already up-to-date.                                                                                                             
mjml_1      | Done in 0.11s.                                                                                                                                                                                                            
mjml_1      | sh: 1: ./convert: not found                                                                                                                                              
karrot-docker_mjml_1 exited with code 127                                                                       
backend_1   | bash: ./sync.py: No such file or directory                                                                                                                   
mjml_1      | yarn install v1.12.3                                                                                                     
mjml_1      | [1/4] Resolving packages...                                                                                                
mjml_1      | success Already up-to-date.                                                                                                
mjml_1      | Done in 0.09s.                                                                                                            
mjml_1      | sh: 1: ./convert: not found                                                                                                                                                                             
karrot-docker_mjml_1 exited with code 127                                                                                
mjml_1      | yarn install v1.12.3                                                                                                         
mjml_1      | [1/4] Resolving packages...                                                                                              
mjml_1      | success Already up-to-date.                                                                                      
mjml_1      | Done in 0.10s.                                                                                                             
mjml_1      | sh: 1: ./convert: not found                                                                                                                        
karrot-docker_mjml_1 exited with code 127                                                           
karrot-docker_backend_1 exited with code 127                                                                                                                      
karrot-docker_backend_1 exited with code 127                                                                                   
frontend_1  | [4/4] Building fresh packages...                                                                                                                                   
frontend_1  | success Saved lockfile.                                                                                                                                            
frontend_1  | Done in 10.22s.                                                                                                                                                                                                           
frontend_1  | yarn run v1.12.3                                                                                                                                                                  
frontend_1  | error Couldn't find a package.json file in "/app"                                                                                                                                                                         
frontend_1  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.                                                                                              
mjml_1      | yarn install v1.12.3                                                                                                                                                                                    
mjml_1      | [1/4] Resolving packages...                                                                                                                                                                          
mjml_1      | success Already up-to-date.                                                                                                                                                                                                                                                   
mjml_1      | Done in 0.06s.                                                                                                                                                                                                                                                                
mjml_1      | sh: 1: ./convert: not found
karrot-docker_mjml_1 exited with code 127                                                                                                                                
frontend_1  | yarn install v1.12.3                                                                
frontend_1  | [1/4] Resolving packages...                                                                                                                                                                                                                                                           
frontend_1  | success Already up-to-date.                                                                                                                                                                                                                                                                                                                                                     frontend_1  | Done in 0.06s.             
frontend_1  | yarn run v1.12.3                                                                    
frontend_1  | error Couldn't find a package.json file in "/app"                                                                                                                                                                         
frontend_1  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.                                 
karrot-docker_frontend_1 exited with code 1                                                                                                                                                                        
mjml_1      | yarn install v1.12.3                                                                                                                        
frontend_1  | yarn install v1.12.3                                         
mjml_1      | [1/4] Resolving packages...                                                                                                                                                                          
mjml_1      | success Already up-to-date.                                                                                                                                                                           
mjml_1      | Done in 0.06s.                                                                 
mjml_1      | sh: 1: ./convert: not found                                                                                                                                                                       
frontend_1  | [1/4] Resolving packages...                                                                                                                                                                            
frontend_1  | success Already up-to-date.                                                           
frontend_1  | Done in 0.06s.                                                                      
karrot-docker_mjml_1 exited with code 127                                                                                                                                                                        
frontend_1  | yarn run v1.12.3                                                     
frontend_1  | error Couldn't find a package.json file in "/app"                                                                                       
frontend_1  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.                                                                                                                   
karrot-docker_frontend_1 exited with code 1                                                                                                                                            
frontend_1  | yarn install v1.12.3                                                                              
frontend_1  | [1/4] Resolving packages...                                                                              
frontend_1  | success Already up-to-date.                                                                                              
frontend_1  | Done in 0.07s.                                                                                                             
frontend_1  | yarn run v1.12.3                                                                                                           
frontend_1  | error Couldn't find a package.json file in "/app"                                                                         
frontend_1  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.                                                                         
karrot-docker_frontend_1 exited with code 1                                                                              
frontend_1  | yarn install v1.12.3
frontend_1  | [1/4] Resolving packages...
frontend_1  | success Already up-to-date.                      
frontend_1  | Done in 0.07s.                                                                      
mjml_1      | yarn install v1.12.3         
mjml_1      | [1/4] Resolving packages...             
mjml_1      | success Already up-to-date. 
mjml_1      | Done in 0.06s.         
mjml_1      | sh: 1: ./convert: not found 
frontend_1  | yarn run v1.12.3            
frontend_1  | error Couldn't find a package.json file in "/app"
frontend_1  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
karrot-docker_mjml_1 exited with code 127 
karrot-docker_frontend_1 exited with code 1
backend_1   | bash: ./sync.py: No such file or directory
frontend_1  | yarn install v1.12.3
frontend_1  | [1/4] Resolving packages...
frontend_1  | success Already up-to-date.
frontend_1  | Done in 0.06s.
frontend_1  | yarn run v1.12.3
frontend_1  | error Couldn't find a package.json file in "/app"
frontend_1  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
karrot-docker_frontend_1 exited with code 1
frontend_1  | yarn install v1.12.3
frontend_1  | [1/4] Resolving packages...
frontend_1  | success Already up-to-date.
frontend_1  | Done in 0.06s.
mjml_1      | yarn install v1.12.3
mjml_1      | [1/4] Resolving packages...
mjml_1      | success Already up-to-date.
mjml_1      | Done in 0.06s.
mjml_1      | sh: 1: ./convert: not found
frontend_1  | yarn run v1.12.3
frontend_1  | error Couldn't find a package.json file in "/app"
frontend_1  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
karrot-docker_mjml_1 exited with code 127
```

Don't have time to look into just now ...

**Comment by nicksellen** [comment]
Looks like it doesn't actually have any of the files. I'd suggest just starting with a fresh setup i.e. this one:
```
git clone https://github.com/yunity/karrot-docker.git
cd karrot-docker
git clone https://github.com/yunity/karrot-frontend.git
git clone https://github.com/yunity/karrot-backend.git
docker-compose up -d
```

**Comment by decentral1se** [comment]
All clear, thanks @nicksellen!

**Comment by snaeil** [comment]
This didn't solve the problem for me.

I am still getting:

```bash
backend_1   |   File "/usr/lib/python3.5/subprocess.py", line 271, in check_call
backend_1   |     raise CalledProcessError(retcode, cmd)
backend_1   | subprocess.CalledProcessError: Command '['/app/env/bin/python3', '-m', 'pip', 'install', '-r', '/tmp/tmpnc_65lco']' returned non-zero exit status 1
backend_1   |
backend_1   |  ★ All done ☺
backend_1   |
backend_1   | Traceback (most recent call last):
backend_1   |   File "./manage.py", line 13, in <module>
backend_1   |     from django.core.management import execute_from_command_line
backend_1   | ImportError: No module named 'django'
backend_1   |
backend_1   |  ★ Installing python dependencies
backend_1   |
backend_1   | Collecting aioredis==1.2.0 (from -r /tmp/tmp7khtf5ub (line 1))
backend_1   |   Using cached https://files.pythonhosted.org/packages/bc/2f/9ad85f5321f3f8604ae0f9b508f53f5f284fdb18b8095d1770f69e551a5e/aioredis-1.2.0-py3-none-any.whl
backend_1   | Collecting apipkg==1.5 (from -r /tmp/tmp7khtf5ub (line 2))
backend_1   |   Using cached https://files.pythonhosted.org/packages/67/08/4815a09603fc800209431bec5b8bd2acf2f95abdfb558a44a42507fb94da/apipkg-1.5-py2.py3-none-any.whl
backend_1   | Collecting argon2-cffi==19.1.0 (from -r /tmp/tmp7khtf5ub (line 3))
backend_1   |   Using cached https://files.pythonhosted.org/packages/1e/14/d7fe69cb4efad2926f85d0ec4736f29fbb6995e2a5bf5501b3cd0173d32b/argon2_cffi-19.1.0-cp34-abi3-manylinux1_x86_64.whl
backend_1   | Collecting asgiref==3.2.2 (from -r /tmp/tmp7khtf5ub (line 4))
backend_1   |   Using cached https://files.pythonhosted.org/packages/d0/39/42344b1060cfb5542eecef3ce6dda3d2d5a89a660716ed5980635985f2a7/asgiref-3.2.2-py2.py3-none-any.whl
backend_1   | Collecting asn1crypto==0.24.0 (from -r /tmp/tmp7khtf5ub (line 5))
backend_1   |   Using cached https://files.pythonhosted.org/packages/ea/cd/35485615f45f30a510576f1a56d1e0a7ad7bd8ab5ed7cdc600ef7cd06222/asn1crypto-0.24.0-py2.py3-none-any.whl
backend_1   | Collecting async-timeout==3.0.1 (from -r /tmp/tmp7khtf5ub (line 6))
backend_1   |   Using cached https://files.pythonhosted.org/packages/e1/1e/5a4441be21b0726c4464f3f23c8b19628372f606755a9d2e46c187e65ec4/async_timeout-3.0.1-py3-none-any.whl
backend_1   | Collecting atomicwrites==1.3.0 (from -r /tmp/tmp7khtf5ub (line 7))
backend_1   |   Using cached https://files.pythonhosted.org/packages/52/90/6155aa926f43f2b2a22b01be7241be3bfd1ceaf7d0b3267213e8127d41f4/atomicwrites-1.3.0-py2.py3-none-any.whl
backend_1   | Collecting attrs==19.1.0 (from -r /tmp/tmp7khtf5ub (line 8))
backend_1   |   Using cached https://files.pythonhosted.org/packages/23/96/d828354fa2dbdf216eaa7b7de0db692f12c234f7ef888cc14980ef40d1d2/attrs-19.1.0-py2.py3-none-any.whl
backend_1   | Collecting autobahn==19.9.2 (from -r /tmp/tmp7khtf5ub (line 9))
backend_1   |   Using cached https://files.pythonhosted.org/packages/08/e1/618bf5abb169ce1ed6574ddd05f68588ab1245e9aa0615d0437b47b2a5ee/autobahn-19.9.2-py2.py3-none-any.whl
backend_1   | Collecting autoflake==1.3.1 (from -r /tmp/tmp7khtf5ub (line 10))
backend_1   |   Using cached https://files.pythonhosted.org/packages/88/88/9a8ae06cc31f68b26078cbbef50ae5df361f4ac0efaafbf03a9fa79ca9c5/autoflake-1.3.1.tar.gz
backend_1   | Collecting automat==0.7.0 (from -r /tmp/tmp7khtf5ub (line 11))
backend_1   |   Using cached https://files.pythonhosted.org/packages/a3/86/14c16bb98a5a3542ed8fed5d74fb064a902de3bdd98d6584b34553353c45/Automat-0.7.0-py2.py3-none-any.whl
backend_1   | Collecting autopep8==1.4.4 (from -r /tmp/tmp7khtf5ub (line 12))
backend_1   |   Using cached https://files.pythonhosted.org/packages/45/f3/24b437da561b6af4840c871fbbda32889ca304fc1f7b6cc3ada8b09f394a/autopep8-1.4.4.tar.gz
backend_1   | Collecting babel==2.7.0 (from -r /tmp/tmp7khtf5ub (line 13))
backend_1   |   Using cached https://files.pythonhosted.org/packages/2c/60/f2af68eb046c5de5b1fe6dd4743bf42c074f7141fe7b2737d3061533b093/Babel-2.7.0-py2.py3-none-any.whl
backend_1   | Collecting backcall==0.1.0 (from -r /tmp/tmp7khtf5ub (line 14))
backend_1   |   Using cached https://files.pythonhosted.org/packages/84/71/c8ca4f5bb1e08401b916c68003acf0a0655df935d74d93bf3f3364b310e0/backcall-0.1.0.tar.gz
backend_1   | Collecting bleach==3.1.0 (from -r /tmp/tmp7khtf5ub (line 15))
backend_1   |   Using cached https://files.pythonhosted.org/packages/ab/05/27e1466475e816d3001efb6e0a85a819be17411420494a1e602c36f8299d/bleach-3.1.0-py2.py3-none-any.whl
backend_1   | Collecting bleach-whitelist==0.0.10 (from -r /tmp/tmp7khtf5ub (line 16))
backend_1   |   Using cached https://files.pythonhosted.org/packages/cf/6b/0c10f2341f5f257b4b47514cd54eaf5bf91b0b52725b71331b2d1cfd3ce7/bleach-whitelist-0.0.10.tar.gz
backend_1   | Collecting cchardet==2.1.4 (from -r /tmp/tmp7khtf5ub (line 17))
backend_1   |   Using cached https://files.pythonhosted.org/packages/fd/8d/654ba71538619de141b4bf17e76fcbc503ef34a552f1c30f7426aa580655/cchardet-2.1.4-cp35-cp35m-manylinux1_x86_64.whl
backend_1   | Collecting certifi==2019.6.16 (from -r /tmp/tmp7khtf5ub (line 18))
backend_1   |   Using cached https://files.pythonhosted.org/packages/69/1b/b853c7a9d4f6a6d00749e94eb6f3a041e342a885b87340b79c1ef73e3a78/certifi-2019.6.16-py2.py3-none-any.whl
backend_1   | Collecting cffi==1.12.3 (from -r /tmp/tmp7khtf5ub (line 19))
backend_1   |   Using cached https://files.pythonhosted.org/packages/62/76/135eeffe0089e6724bdd65c1bf9f1654db9b47783e65b8d9f1454c540d8b/cffi-1.12.3-cp35-cp35m-manylinux1_x86_64.whl
backend_1   | Collecting channels==2.3.0 (from -r /tmp/tmp7khtf5ub (line 20))
backend_1   |   Using cached https://files.pythonhosted.org/packages/20/4d/e2e4efda2804bdb9151177035bd48c1e88aad300b7e40e11cf1c7ca82030/channels-2.3.0-py2.py3-none-any.whl
backend_1   | Collecting channels-redis==2.4.0 (from -r /tmp/tmp7khtf5ub (line 21))
backend_1   |   ERROR: Could not find a version that satisfies the requirement channels-redis==2.4.0 (from -r /tmp/tmp7khtf5ub (line 21)) (from versions: 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.1.0, 2.1.1, 2.2.0, 2.2.1, 2.3.0, 2.3.1, 2.3.2)
backend_1   | ERROR: No matching distribution found for channels-redis==2.4.0 (from -r /tmp/tmp7khtf5ub (line 21))
backend_1   | Traceback (most recent call last):
backend_1   |   File "/app/env/bin/pip-sync", line 10, in <module>
backend_1   |     sys.exit(cli())
backend_1   |   File "/app/env/lib/python3.5/site-packages/click/core.py", line 764, in __call__
backend_1   |     return self.main(*args, **kwargs)
backend_1   |   File "/app/env/lib/python3.5/site-packages/click/core.py", line 717, in main
backend_1   |     rv = self.invoke(ctx)
backend_1   |   File "/app/env/lib/python3.5/site-packages/click/core.py", line 956, in invoke
backend_1   |     return ctx.invoke(self.callback, **ctx.params)
backend_1   |   File "/app/env/lib/python3.5/site-packages/click/core.py", line 555, in invoke
backend_1   |     return callback(*args, **kwargs)
backend_1   |   File "/app/env/lib/python3.5/site-packages/piptools/scripts/sync.py", line 139, in cli
backend_1   |     install_flags=install_flags,
backend_1   |   File "/app/env/lib/python3.5/site-packages/piptools/sync.py", line 195, in sync
backend_1   |     + install_flags
backend_1   |   File "/usr/lib/python3.5/subprocess.py", line 271, in check_call
backend_1   |     raise CalledProcessError(retcode, cmd)
backend_1   | subprocess.CalledProcessError: Command '['/app/env/bin/python3', '-m', 'pip', 'install', '-r', '/tmp/tmp7khtf5ub']' returned non-zero exit status 1
backend_1   |
backend_1   |  ★ All done ☺
backend_1   |
backend_1   | Traceback (most recent call last):
backend_1   |   File "./manage.py", line 13, in <module>
backend_1   |     from django.core.management import execute_from_command_line
backend_1   | ImportError: No module named 'django'
karrot-docker_backend_1 exited with code 1
```

**Comment by nicksellen** [comment]
I could recreate some similar error locally, and just updated the python image to resolve it (see https://github.com/yunity/karrot-docker/commit/f2c7ad2c0fd77bbb260e9abc170848044a081766).

**Comment by snaeil** [comment]
Didn't you get a new error like me?

db:
```bash
Attaching to karrot-docker_db_1
db_1        | LOG:  database system was shut down at 2019-10-01 17:46:13 UTC
db_1        | LOG:  MultiXact member wraparound protections are now enabled
db_1        | LOG:  database system is ready to accept connections
db_1        | LOG:  autovacuum launcher started
db_1        | LOG:  incomplete startup packet
```

backend:
```bash
Attaching to karrot-docker_backend_1
backend_1   | Could not find platform independent libraries <prefix>
backend_1   | Could not find platform dependent libraries <exec_prefix>
backend_1   | Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
backend_1   | Fatal Python error: Py_Initialize: Unable to get the locale encoding
backend_1   | ImportError: No module named 'encodings'
backend_1   | 
backend_1   | Current thread 0x00007f60ea071740 (most recent call first):
backend_1   | bash: line 1:     9 Aborted                 (core dumped) ./sync.py --no-mjml
backend_1   | Could not find platform independent libraries <prefix>
backend_1   | Could not find platform dependent libraries <exec_prefix>
backend_1   | Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
backend_1   | Fatal Python error: Py_Initialize: Unable to get the locale encoding
backend_1   | ImportError: No module named 'encodings'
backend_1   | 
backend_1   | Current thread 0x00007f2954080740 (most recent call first):
backend_1   | bash: line 1:     9 Aborted                 (core dumped) ./sync.py --no-mjml
backend_1   | Could not find platform independent libraries <prefix>
backend_1   | Could not find platform dependent libraries <exec_prefix>
backend_1   | Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
backend_1   | Fatal Python error: Py_Initialize: Unable to get the locale encoding
backend_1   | ImportError: No module named 'encodings'
backend_1   | 
backend_1   | Current thread 0x00007ff926453740 (most recent call first):
backend_1   | bash: line 1:     9 Aborted                 (core dumped) ./sync.py --no-mjml
backend_1   | Could not find platform independent libraries <prefix>
backend_1   | Could not find platform dependent libraries <exec_prefix>
backend_1   | Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
backend_1   | Fatal Python error: Py_Initialize: Unable to get the locale encoding
backend_1   | ImportError: No module named 'encodings'
backend_1   | 
backend_1   | Current thread 0x00007f2e0a082740 (most recent call first):
backend_1   | bash: line 1:     9 Aborted                 (core dumped) ./sync.py --no-mjml
backend_1   | Could not find platform independent libraries <prefix>
backend_1   | Could not find platform dependent libraries <exec_prefix>
backend_1   | Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
backend_1   | Fatal Python error: Py_Initialize: Unable to get the locale encoding
backend_1   | ImportError: No module named 'encodings'
backend_1   | 
backend_1   | Current thread 0x00007f3bdf778740 (most recent call first):
backend_1   | bash: line 1:     9 Aborted                 (core dumped) ./sync.py --no-mjml
backend_1   | Could not find platform independent libraries <prefix>
backend_1   | Could not find platform dependent libraries <exec_prefix>
backend_1   | Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
backend_1   | Fatal Python error: Py_Initialize: Unable to get the locale encoding
backend_1   | ImportError: No module named 'encodings'
backend_1   | 
backend_1   | Current thread 0x00007f0099e42740 (most recent call first):
backend_1   | bash: line 1:    10 Aborted                 (core dumped) ./sync.py --no-mjml
backend_1   | Could not find platform independent libraries <prefix>
backend_1   | Could not find platform dependent libraries <exec_prefix>
backend_1   | Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
backend_1   | Fatal Python error: Py_Initialize: Unable to get the locale encoding
backend_1   | ImportError: No module named 'encodings'
backend_1   | 
backend_1   | Current thread 0x00007fc381c1c740 (most recent call first):
backend_1   | bash: line 1:     9 Aborted                 (core dumped) ./sync.py --no-mjml
backend_1   | Could not find platform independent libraries <prefix>
backend_1   | Could not find platform dependent libraries <exec_prefix>
backend_1   | Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
backend_1   | Fatal Python error: Py_Initialize: Unable to get the locale encoding
backend_1   | ImportError: No module named 'encodings'
backend_1   | 
backend_1   | Current thread 0x00007f260e100740 (most recent call first):
backend_1   | bash: line 1:     9 Aborted                 (core dumped) ./sync.py --no-mjml

```

**Comment by snaeil** [comment]
I forgot to remove the volumes with `docker-compose down -v`.
It's working now, thanks!
